<a href="https://colab.research.google.com/github/EliGorniak/100DaysOfDSCode/blob/master/iaexpert_python_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1. Manipulação de variáveis e constantes

## Variáveis e constantes

- Por meio de variáveis que um algortimo “guarda” os dados do problema
- Todo dado que tem a possibilidade de ser alterado no decorrer do tempo deverá ser tratado como uma variável
- Quando um dado não tem nenhuma possibilidade de variar no decorrer do tempo, deverá ser tratado como constante

Exemplo: calcular a área de um triângulo. Sabemos que a fórmula para o cálculo da área de um triângulo é BASE * ALTURA / 2. **Base** e **altura** são dados que irão variar no decorrer do “tempo de execução”. O número 2 da fórmula é um dado constante, pois sempre terá o mesmo valor

## Tipo de variáveis

- Inteiros: valores positivos ou negativos, que não possuem uma parte fracionária. Exemplos: 1, 30, 40, 12, -50
- Float (real): valores positivos ou negativos, que podem possuir uma parte fracionária (também podem ser inteiros). Exemplos: 1.4, 6.7, 10.3, 100, -47
- Caracteres (char ou string): qualquer elemento presente no teclado. Exemplos: “Maria”, “João”, ‘M’, ‘F’
- Lógico (boleano): verdadeiro ou falso. Exemplos: true, false, 1, 0

## Variáveis inteiras

In [ ]:
numero = -3
numero_jogos = 14
numero_convidados = 15

In [ ]:
numero

-3

In [ ]:
print(numero)

-3


In [ ]:
print(numero, numero_convidados)

-3 15


## Variáveis float (ponto flutuante)

In [1]:
pi = 3.14
numero_euler = 2.71
escala_terremoto = -4.55

In [2]:
print(pi)
print(numero_euler)
print(escala_terremoto)

3.14
2.71
-4.55


## Strings e chars

In [ ]:
letra = 'a'
palavra1 = 'linguagem de programação'
palavra2 = 'Python'

In [ ]:
print(letra, palavra1)

a linguagem de programação


In [ ]:
print('Estou aprendendo uma', palavra1)

Estou aprendendo uma linguagem de programação


In [ ]:
print('Esta', palavra1, 'se chama', palavra2)

Esta linguagem de programação se chama Python


In [ ]:
idade = int(input('Digite sua idade:'))
print('Sua idade é ', idade)

Digite sua idade:21
Sua idade é  21


In [3]:
pH = float(input('Qual o pH do solo durante a última medição? '))
print('O pH medido foi ', pH)

Qual o pH do solo durante a última medição? 2.5
O pH medido foi  2.5


In [ ]:
nome = str(input('Qual o seu nome?'))
print('Seu nome é', nome)

Qual o seu nome?Jones
Seu nome é Jones


In [ ]:
idade

21

# Aula 2. Manipulação de Strings

In [4]:
a = 'casaco'
print(a)

casaco


In [5]:
maiuscula = a.upper()
print(maiuscula)

CASACO


In [6]:
minuscula = maiuscula.lower()
print(minuscula)

casaco


In [7]:
capital = a.capitalize()
print(capital)

Casaco


In [8]:
# extrair partes da string pelo índice
metade_palavra = a[0:3] # de zero a 3
print(metade_palavra)

cas


In [10]:
# extrair as ultimas letras
ultimas_letras = a[3:] # da posição 3 até o final (posições 3, 4 e 5)
print(ultimas_letras)

aco


In [12]:
# para substituir algum caractere dentro da string
b = a.replace('aco', 'inha') # substituindo onde tem 'aco' por 'inha' na string
print(a)
print(b)

casaco
casinha


In [13]:
c = a. replace('o', 'a')
print(c)

casaca


In [14]:
# metodo para achar algum elemento dentro da string
c.find('s') # a resposta vai indicar o índice/posição dentro da string

2

In [15]:
# se houver mais de um caracter igual, vai retornar a posição de apenas O PRIMEIRO encontrado
c.find('a')

1

In [16]:
# se tentar achar um caracter que não existe, ele vai retornar -1 ou FALSO
c.find('b')

-1

In [17]:
# tamanho da string - vai contar inclusive os espaços em branco:
e = ' casaco '
print(len(e))

8


In [19]:
# para retirar os espaços em branco antes e depois
f = e.strip()
print(f)
print(len(f))

casaco
6


In [20]:
# usando f para indicar formatação e uso das variáveis concatenadas dentro da string:
n1 = 14
n2 = 16
print(f'Dividindo {n1} por {n2} o resultado é {n1/n2}.')

Dividindo 14 por 16 o resultado é 0.875.


# Aula 3. Operações matemáticas

In [21]:
a = 5
b = 3
print(a + b)

8


In [22]:
a + b

8

In [27]:
# operações matematicas:
print('A soma é ', a + b)
print('A subtração é ', a - b)
print('A multiplicação é', a * b)
print('A divisão é', a/b)
print('O resto da divisão é', a%b) #vai devolver o que sobra da divisão
print('5 elevado a 3 é', 5**3) # numero elevado a uma potencia


A soma é  8
A subtração é  2
A multiplicação é 15
A divisão é 1.6666666666666667
O resto da divisão é 2
5 elevado a 3 é 125


In [28]:
# para extrair a raiz quadrada, importar a biblioteca MATH
import math 
math.sqrt(81)

9.0

## **Arredondamento**

In [33]:
casos_doenca = 134
numero_habitantes = 34432
casos_por_habitante = casos_doenca / numero_habitantes
print(casos_por_habitante)

0.003891728624535316


In [36]:
# para arredondar o resultado, usar a função ROUND e o numero de casas decimais desejadas
round(casos_por_habitante, 6)
print('O número de casos por habitante é de', round(casos_por_habitante, 4))

O número de casos por habitante é de 0.0039


#### **Exercicios de fixação**

**1. Ler dois números inteiros, executar e mostrar o resultado das seguintes operações: adição, subtração, multiplicação e divisão**

In [46]:
numero1 = int(input('Digite um número:'))
numero2 = int(input('Digite um número:'))
print('adição dos dois números:', numero1 + numero2)
print('subtração dos dois números:', numero1 - numero2)
print('multiplicação dos dois números:', numero1 * numero2)
print('divisão dos dois números:', round(numero1 / numero2, 2))

Digite um número:5
Digite um número:3
adição dos dois números: 8
subtração dos dois números: 2
multiplicação dos dois números: 15
divisão dos dois números: 1.67


**2. Efetuar o cálculo da quantidade de litros de combustível gasto em uma viagem, utilizando um automóvel que faz 12 Km por litro. Para obter o cálculo, o usuário deve fornecer o tempo gasto na viagem e a velocidade média durante ela. Desta forma, será possível obter a distância percorrida com a fórmula DISTANCIA = TEMPO * VELOCIDADE. Tendo o valor da distância, basta calcular a quantidade de litros de combustível utilizada na viagem, com a fórmula: LITROS_USADOS = DISTANCIA / 12. O programa deve apresentar os valores da velocidade média, tempo gasto na viagem, a distância percorrida e a quantidade de litros utilizada na viagem.**

In [48]:
consumo = 12
tempo_viagem = float(input('Digite o tempo de viagem: '))
velocidade = float(input('Digite a velocidade média: '))
distancia_percorrida = tempo_viagem * velocidade
consumo_total = round(distancia_percorrida / consumo, 2)
print(f'A velocidade média foi de {velocidade}km/h, o tempo gasto foi de {tempo_viagem} horas, a distancia total percorrida foi de {distancia_percorrida} km e o consumo total foi de {consumo_total} litros.')

Digite o tempo de viagem: 3.5
Digite a velocidade média: 80
A velocidade média foi de 80.0km/h, o tempo gasto foi de 3.5 horas, a distancia total percorrida foi de 280.0 km e o consumo total foi de 23.33 litros.


# Aula 4. Operadores lógicos e relacionais

## 4.1 Operadores lógicos

In [50]:
a = True
b = False
print(a, b)

True False


In [51]:
a and b

False

In [52]:
a & b

False

In [54]:
c = a and b
print('A e B são iguais é:', c) # para usar aspas dentro da string, usar aspas duplas por fora e dentro simples: "'A' e 'B' são iguais é"

A e B são iguais é: False


In [55]:
a or b

True

In [56]:
a | b

True

In [58]:
d = a or b
print("'A' ou 'B' é igual a", d)

'A' ou 'B' é igual a True


In [59]:
not a

False

In [60]:
not b

True

## 4.2 Operadores relacionais

In [63]:
5 > 3

True

In [64]:
5 < 3

False

In [65]:
5 >= 5

True

In [67]:
5 <= 3

False

In [68]:
5 == 3

False

In [69]:
5 != 3

True

## 4.3 Operadores condicionais - if, else

In [70]:
if 5 > 3:
  print('5 é maior que 3')

5 é maior que 3


In [72]:
# 2 condições:
if 5 > 6:
  print('5 é maior')
else:
  print('5 não é maior')

5 não é maior


In [75]:
# mais de 2 condições:
n = 9
if n == 4:
  print('n é igual a 4')
else:
  if n == 3:
    print('n é igual a 3')
  else:
    print('n não é igual a 4 nem 3')

n não é igual a 4 nem 3


In [79]:
x = 4
y = 3
if (x > 1) and (y % 2 == 0):
  print('x é maior que 2 e y é par.')
else:
  print('Uma apenas ou nenhuma das condições foram satisfeitas.')

Uma apenas ou nenhuma das condições foram satisfeitas.


#### **Exercicios de fixação**

1. Leia a idade do usuário e classifique-o em:
* Criança – 0 a 12 anos
* Adolescente – 13 a 17 anos
* Adulto – acima de 18 anos
* Se o usuário digitar um número negativo, mostrar a mensagem que a idade é inválida.

In [92]:
idade = int(input('Digite sua idade: '))
if (idade <= 12):
  print(f'Sua idade é {idade}, portanto, Criança.')
elif (idade >= 13 and idade <= 18):
  print(f'Sua idade é {idade}, portanto, Adolescente.')
elif (idade > 18):
  print(f'Sua idade é {idade}, portanto, Adulto.')
else:
  print('Idade inválida. Digite novamente.')

Digite sua idade: 88
Sua idade é 88, portanto, Adulto.


2. Calcular a média de um aluno que cursou a disciplina de Programação I, a partir da leitura das notas M1, M2 e M3; passando por um cálculo da média aritmética. Após a média calculada, devemos anunciar se o aluno foi aprovado, reprovado ou pegou exame:
* Se a média estiver entre 0.0 e 4.0, o aluno está reprovado
* Se a média estiver entre 4.1 e 6.0, o aluno pegou exame
* Se a média for maior do que 6.0, o aluno está aprovado
* Se o aluno pegou exame, deve ser lida a nota do exame. Se a nota do exame for maior do que 6.0, está aprovado, senão; está reprovado.

In [106]:
m1 = float(input('Digite a primeira nota: '))
m2 = float(input('Digite a segunda nota: '))
m3 = float(input('Digite a terceira nota: '))
media = (m1 + m2 + m3)/3
print('Sua média é', round(media, 2))
if (media <= 4.0):
  print('Você reprovou!')
elif (media >= 4.1 and media <= 6.0):
  print('Você pegou exame!')
  exame = float(input('Digite a nota do seu exame: '))
  if (exame > 6.0):
    print('Você está aprovado no exame!')
  else:
    print('Você reprovou no exame!')
elif (media > 6.0):
  print('Você está aprovado!')

Digite a primeira nota: 5
Digite a segunda nota: 6
Digite a terceira nota: 4
Sua média é 5.0
Você pegou exame!
Digite a nota do seu exame: 5
Você reprovou no exame!


# Aula 5. Estruturas de repetição

## 5.1 Estrutura de repetição - For

In [107]:
for numero in range(1,5): #imprime de 1 a 4, o ultimo numero não imprime!
  print(numero)

1
2
3
4


In [109]:
for numero in range(5, 0, -1): # o terceiro parametro é o step, de quantos em quantos
  print(numero)

5
4
3
2
1


In [112]:
soma = 0
for numero in range (1, 6):
  soma = soma + numero
  print(soma)
print(soma)

1
3
6
10
15
15


In [114]:
# como utilizar o for para percorrer strings:
palavra = 'sorvete'
for letra in palavra:
  print(letra)
  if letra == 'v':
    print('Achou a letra v!')

s
o
r
v
Achou a letra v!
e
t
e


In [117]:
# como utilizar o for aninhado, excelente para percorrer matrizes
for i in range(0,5):
  print(i)
  print('---')
  for j in range (0,3): # para cada i impresso, ele vai imprimir 0, 1 e 2
    print(j)
  print()

0
---
0
1
2

1
---
0
1
2

2
---
0
1
2

3
---
0
1
2

4
---
0
1
2



## 5.2 Estrutura de repetição - While

In [122]:
# sempre que trabalhar com while precisa usar um break, senão vai ficar rodando até o final da memoria!
# SEMPRE definir uma variavel fora do while
numero = 1 
while numero < 6: # SEMPRE definir uma condição
  print(numero)
  numero += 1 # SEMPRE colocar um incremento para evitar o loop infinito!!!!!!!!!!!  
print('- - -')

1
2
3
4
5
- - -


In [123]:
# while invertido
numero = 5
while numero > 0:
  print(numero)
  numero -= 1

5
4
3
2
1


In [126]:
soma = 0
numero = 1
while numero < 6:
  soma += numero
  print(soma)
  numero += 1
  print(numero)
  ('...')
print(soma)

1
2
3
3
6
4
10
5
15
6
15


In [127]:
# usando o while quando o usuario precisa digitar algum input
# semelhante a uma validação do input do usuario
numero = -1
while numero < 1 or numero > 10:
  numero = int(input('Digite um numerode 1 a 10: ')) # enquanto o usuario digitar qualquer numero fora do range, ele vai continuar executando...
# enquanto a condição for FALSA, ele continua executando o loop.
# quando a condição for VERDADEIRA, ele pára a execução

Digite um numerode 1 a 10: 12
Digite um numerode 1 a 10: 7


#### **Exercicios de fixação**

1. Ler 5 notas e informar a média.

In [137]:
# usando FOR:
soma_notas = 0
n_notas = 5
for _ in range(n_notas): # usa-se _ para substituir a definição de alguma variavel que não vai ser utilizada posteriormente, apenas para percorrer o FOR
  soma_notas = float(input('Digite uma nota: ')) + soma_notas
  # print(soma_notas)
media = soma_notas / n_notas
print(f'A média é {media}.')

Digite uma nota: 9
Digite uma nota: 8
Digite uma nota: 7
Digite uma nota: 6
Digite uma nota: 9
A média é 7.8.


In [142]:
# usando o WHILE:
numero = 1
while numero <= 5:
  nota = float(input("Digite a nota: "))
  soma += nota
  numero += 1
print('A média é ', soma/5)

Digite a nota: 9
Digite a nota: 8
Digite a nota: 7
Digite a nota: 6
Digite a nota: 5
A média é  15.6


2. Imprimir a tabuada do número 3 (3 x 1 = 1 – 3 x 10 = 30)

In [155]:
 # usando FOR:
valor = int(input('Digite um numero para ver a tabuada: '))
for numero in range (1, 11):
  print(f'{valor} x {numero} = {valor * numero}')

Digite um numero para ver a tabuada: 8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


In [145]:
# usando WHILE:
numero_tabuada = 1
while numero_tabuada <= 10:
  print('3 x {} = {}'.format(numero_tabuada, 3 * numero_tabuada))
  numero_tabuada += 1

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


# Aula 6. Coleções

## 6.1 Tuplas - usa ( )

In [150]:
tupla = ('Homo sapiens', 'Canis familiaris', 'Felis catus')
tupla

('Homo sapiens', 'Canis familiaris', 'Felis catus')

In [153]:
# traz o conteudo na posição 1
tupla[1]

'Canis familiaris'

In [154]:
# mostra em que posição está determinado item
tupla.index('Canis familiaris')

1

In [156]:
# verificar cada um dos elementos dentro da lista
for elemento in tupla:
  print(elemento)

Homo sapiens
Canis familiaris
Felis catus


## 6.2 Listas - usa [ ] e permite armazenar mais valores

In [158]:
lista_1 = ['Homo sapiens', 'Canis familiaris', 'Felis catus']
lista_2 = ['Xenopus laevis', 'Ailuropoda melanoleuca']
lista_3 = lista_1 + lista_2
print(lista_3)

['Homo sapiens', 'Canis familiaris', 'Felis catus', 'Xenopus laevis', 'Ailuropoda melanoleuca']


In [159]:
# é possível multiplicar ou replicar o conteúdo de uma lista
lista_2_2 = lista_2 * 2
print(lista_2_2)

['Xenopus laevis', 'Ailuropoda melanoleuca', 'Xenopus laevis', 'Ailuropoda melanoleuca']


In [160]:
# para visualizar apenas o elemento do indice 0
lista_1[0]

'Homo sapiens'

In [161]:
# para visualizar mais de um elemento na lista
lista_1[0:2] # lembrando que ele não traz o último!!!!!!!!!!!

['Homo sapiens', 'Canis familiaris']

In [163]:
# adicionando itens na lista
lista_1.append('Gorila gorila')
print(lista_1)

['Homo sapiens', 'Canis familiaris', 'Felis catus', 'Gorila gorila', 'Gorila gorila']


In [164]:
# removendo algum item desta lista
lista_1.remove('Gorila gorila')
print(lista_1)

['Homo sapiens', 'Canis familiaris', 'Felis catus', 'Gorila gorila']


In [165]:
# para deletar uma lista
del(lista_2)
print(lista_3)

['Homo sapiens', 'Canis familiaris', 'Felis catus', 'Xenopus laevis', 'Ailuropoda melanoleuca']


In [166]:
# para percorrer cada um dos elementos de uma lista, pode-se usar o FOR
for item in lista_2_2:
  print(item)

Xenopus laevis
Ailuropoda melanoleuca
Xenopus laevis
Ailuropoda melanoleuca


## 6.3 Dicionários - usam { } e carregam o conceito de chave e valor

In [167]:
coleta = {'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anopheles darlingi': 14}

In [168]:
coleta['Aedes aegypt']

32

In [169]:
# para adicionar um novo item no dicionario
coleta['Rhodnius montenegrensis'] = 11
print(coleta)

{'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anopheles darlingi': 14, 'Rhodnius montenegrensis': 11}


In [170]:
# para apagar um item
del(coleta)['Rhodnius montenegrensis']
print(coleta)

{'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anopheles darlingi': 14}


In [175]:
# para visualizar os itens do dicionario
coleta.items()

dict_items([('Aedes aegypt', 32), ('Aedes albopictus', 22), ('Anopheles darlingi', 14)])

In [176]:
# para visualizar as chaves do dicionario
coleta.keys()

dict_keys(['Aedes aegypt', 'Aedes albopictus', 'Anopheles darlingi'])

In [177]:
# para visualizar os valores no dicionario
coleta.values()

dict_values([32, 22, 14])

In [178]:
# juntar 2 dicionarios
coleta2 = {'Anopheles gambiae': 13, 'Anopheles daeneorum': 14}

In [179]:
# após criar o novo dicionario
coleta.update(coleta2) # primeiro dicionario + metodo update e como parametro o dicionario a ser incorporado no primeiro
print(coleta)

{'Aedes aegypt': 32, 'Aedes albopictus': 22, 'Anopheles darlingi': 14, 'Anopheles gambiae': 13, 'Anopheles daeneorum': 14}


In [180]:
# ver todos os itens agora com os 2 dicionarios adicionados
coleta.items()

dict_items([('Aedes aegypt', 32), ('Aedes albopictus', 22), ('Anopheles darlingi', 14), ('Anopheles gambiae', 13), ('Anopheles daeneorum', 14)])

In [182]:
for especie, num_especimes in coleta.items(): # especie é a chave, num_especimes é o valor
  print(f'Espécie: {especie} | Número de especimes: {num_especimes}.')

Espécie: Aedes aegypt | Número de especimes: 32.
Espécie: Aedes albopictus | Número de especimes: 22.
Espécie: Anopheles darlingi | Número de especimes: 14.
Espécie: Anopheles gambiae | Número de especimes: 13.
Espécie: Anopheles daeneorum | Número de especimes: 14.


## 6.4 Conjuntos (set)

In [184]:
biomoleculas = ('proteina', 'ácidos nucleicos', 'carboidrato', 'lipídeo', 'ácidos nucleicos', 'carboidrato', 'carboidrato', 'carboidrato')
print(biomoleculas)

('proteina', 'ácidos nucleicos', 'carboidrato', 'lipídeo', 'ácidos nucleicos', 'carboidrato', 'carboidrato', 'carboidrato')


In [185]:
print(set(biomoleculas)) # vai trazer apenas os itens únicos, sem repetição

{'proteina', 'carboidrato', 'lipídeo', 'ácidos nucleicos'}


In [188]:
conj1 = {1,2,3,4,5}
conj2 = {3,4,5,6,7}
conj3 = conj1.intersection(conj2) # a função intersection vai trazer apenas os itens que estão presentes nos 2 conjuntos analisados
print(conj3)

{3, 4, 5}


In [189]:
# calculo da diferença entre os conjuntos - vai retornar apenas os itens que estão presentes no C1 mas NÃO ESTÃO NO c2
conj1.difference(conj2)

{1, 2}

In [190]:
conj2.difference(conj1) # vai trazer apenas os itens que estão presentes no C2 mas nao estão no C1

{6, 7}

## 6.5 Matrizes - precisa da biblioteca Numpy para processamento dos calculos matematicos

In [192]:
import numpy as np

In [199]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]]) # 2 linhas e 3 colunas
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [198]:
# traz o formato da matriz
matriz.shape 

(2, 3)

In [197]:
# traz tudo que ocupa a posição 0 dentro do array
matriz [0] 

array([2, 3, 1])

In [200]:
# traz tudo que ocupa a posição 1 dentro do array
matriz[1]

array([4, 5, 7])

In [202]:
# traz de dentro do conjunto da posição 0, o elemento na posição 1
matriz[0][2]

1

In [203]:
# traz de dentro do conjunto da posição 1, o elemento na posição 2
matriz[1][2]

7

In [205]:
# percorrer todos os elementos do array
for i in range(matriz.shape[0]): # vai percorrer as linhas
  print(matriz[i])
  for j in range(matriz.shape[1]): # vai percorrer as colunas dentro de cada um dos i = cada linha
    print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7


#### **Exercicios de fixação**

1. **Lista**: Crie uma estrutura de repetição para fazer a leitura de 5 números inteiros e os armazene dentro de uma lista. Após a leitura, crie outra estrutura de repetição para somar todos os valores digitados

In [230]:
lista = []
for i in range(0, 5):
  numero = int(input("Digite um numero: "))
  lista.append(numero)
print(lista)

# usando FOR
soma = 0
for item in lista:
  soma += item
print(soma)

Digite um numero: 1
Digite um numero: 2
Digite um numero: 3
Digite um numero: 4
Digite um numero: 5
[1, 2, 3, 4, 5]
15


In [233]:
# usando NUMPY
import numpy as np
np.array(lista).sum()

15

2. **Dicionário**: Crie um dicionário para armazenar o nome e a nota de 3 alunos, fazendo a leitura dos valores por meio de uma estrutura de repetição. Depois, crie uma nova estrutura de repetição para somar todas as notas e retornar a média

In [238]:
alunos = {}
for item in range(1, 4):
  nome = str(input('Digite o nome do aluno: '))
  nota = float(input('Digite a nota: '))
  alunos[nome] = nota
print(alunos)

Digite o nome do aluno: joao
Digite a nota: 9
Digite o nome do aluno: ana
Digite a nota: 8
Digite o nome do aluno: jose
Digite a nota: 7
{'joao': 9.0, 'ana': 8.0, 'jose': 7.0}


In [241]:
# qual a nota da Ana?
alunos['ana']

8.0

In [242]:
# cálculo da média
soma = 0
for i in alunos.values():
  soma += i
media = soma / 3
print(f'Média: {media}')

Média: 8.0


3. **Matriz**: Dada a matriz abaixo, construa uma estrutura de repetição para percorrer e somar todos os elementos da matriz
matriz = np.array([[3, 4, 1], [3, 1, 5]])

In [218]:
matrizz = np.array([[3, 4, 1], [3, 1, 5]])

In [245]:
total = 0
for i in range(matrizz.shape[0]):
  for j in range(matrizz.shape[1]):
    total += matrizz[i][j]
print(f'Soma dos valores é {total}.')

Soma dos valores é 17.
